name: plant_collector
description: Create a digital collection of all your plants
# Always remember to update the version number
# 2021-01-22
# TODO version number, and version code
version: 1.6.0+12

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity: ^2.0.2
  cupertino_icons: ^1.0.0
#  downloads path for export
  downloads_path_provider: ^0.1.0
#  support for import/export of collection to csv
  csv: ^4.1.0
#  this package is needed to check version for android sdk 29 +
#  device_info: ^0.4.2+1
  provider: ^4.3.3
  modal_progress_hud: ^0.1.3
  path_provider: ^1.6.27
  path: ^1.7.0
  image_picker: ^0.6.7
  carousel_slider: ^2.3.1
  photo_view: ^0.10.3
# ***iOS - must comment out the below line, uncomment for Android
  flutter_exif_rotation: 0.3.1
  image: ^2.1.19
  date_format: ^1.0.9
#  FIREBASE
  firebase_storage: ^7.0.0
# ***iOS - WORKAROUND - remove ^ in line of code below, add back for Android
  # 0.15.4 works for iOS
  firebase_auth: ^0.20.0
  cloud_firestore: ^0.16.0
#  this may have to be lower to 6.0.0 or so
  firebase_messaging: ^6.0.16
#  SIGN IN
#  google_sign_in: ^4.1.4
  splashscreen: ^1.3.5
  cached_network_image: ^2.1.0
  flare_flutter: ^2.0.6
  expandable: ^4.1.4
#  flutter_material_color_picker: ^1.0.5
#  reorderables: ^0.2.12
  share: ^0.6.5
  flutter_local_notifications: ^3.0.3
  url_launcher: ^5.7.10

# ***iOS - WORKAROUND - comment out for Android
#dependency_overrides:
#  firebase_core: 0.4.4

dev_dependencies:
# ***iOS - WORKAROUND - may have to comment out the following two lines to get running on iOS
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/badges/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
