name: plant_collector
description: Create a digital collection of all your plants
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^3.1.0
  modal_progress_hud: ^0.1.3
  path_provider: ^1.3.0
  path: ^1.6.4
  image_picker: ^0.6.2
  carousel_slider: ^1.3.0
  photo_view: ^0.6.0
  flutter_exif_rotation: ^0.2.6
  image: ^2.1.5
  date_format: ^1.0.8
  firebase_core: ^0.4.0+9
  firebase_storage: ^3.0.6
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  splashscreen: ^1.2.0
  cached_network_image: ^1.1.3
  flare_flutter: ^1.7.1
  expandable: ^3.0.1
  flutter_material_color_picker: ^1.0.5
#  get this up and running for group sorting functions
  reorderables: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
